### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Pravesh001** [hlamba28/Offline-Signature-Verification-using-Siamese-Network#1]
please write requirements.txt as many tensorflow functions are deprecated and will be removed in future versions. by this file we can make a virtual environment for the project so that it runs well.
please tell me if there is a way to extract feature of these signature pic as this is really huge data.

**Comment by hlamba28** [comment]
Hi Pravesh,

You can use any version of tensorflow >= 1.9.0 and Keras >= 2.0.0

Regarding feature extraction, Convolutional Neural Networks are responsible for that. I have not done any manual feature extraction.
